spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: "b598eccbed8ea78f52b8"
            client-secret: "3199790811fb616e6e7429f377112c7d183b73d5"
